describe("matchers", function()
  local matchers = require("nvim-project-config.matchers")

  describe("process", function()
    it("nil returns always-true matcher", function()
      local m = matchers.process(nil)
      assert.is_true(m("anything"))
      assert.is_true(m("/some/path/file.lua"))
      assert.is_true(m(""))
    end)

    it("string matches exact basename", function()
      local m = matchers.process("init.lua")
      assert.is_true(m("/home/user/project/init.lua"))
      assert.is_true(m("init.lua"))
      assert.is_false(m("/home/user/project/main.lua"))
      assert.is_false(m("init.luax"))
    end)

    it("table matches if any match (OR)", function()
      local m = matchers.process({ "a.lua", "b.lua" })
      assert.is_true(m("/path/to/a.lua"))
      assert.is_true(m("/path/to/b.lua"))
      assert.is_false(m("/path/to/c.lua"))
    end)

    it("function is called directly", function()
      local called_with = nil
      local m = matchers.process(function(path)
        called_with = path
        return path:match("%.lua$") ~= nil
      end)
      assert.is_true(m("test.lua"))
      assert.equals("test.lua", called_with)
      assert.is_false(m("test.py"))
    end)
  end)

  describe("any", function()
    it("returns true if any matcher matches", function()
      local m = matchers.any("foo.lua", "bar.lua")
      assert.is_true(m("/path/foo.lua"))
      assert.is_true(m("/path/bar.lua"))
      assert.is_false(m("/path/baz.lua"))
    end)

    it("works with mixed matcher types", function()
      local m = matchers.any("exact.lua", function(p)
        return p:match("custom") ~= nil
      end)
      assert.is_true(m("/path/exact.lua"))
      assert.is_true(m("/path/custom_file.txt"))
      assert.is_false(m("/path/other.lua"))
    end)

    it("returns false for empty matchers", function()
      local m = matchers.any()
      assert.is_false(m("anything"))
    end)
  end)

  describe("all", function()
    it("returns true only if all matchers match", function()
      local m = matchers.all(
        function(p) return p:match("%.lua$") ~= nil end,
        function(p) return p:match("test") ~= nil end
      )
      assert.is_true(m("test_file.lua"))
      assert.is_false(m("test_file.py"))
      assert.is_false(m("main.lua"))
    end)

    it("returns true for empty matchers", function()
      local m = matchers.all()
      assert.is_true(m("anything"))
    end)
  end)

  describe("not_", function()
    it("negates a string matcher", function()
      local m = matchers.not_("excluded.lua")
      assert.is_false(m("/path/excluded.lua"))
      assert.is_true(m("/path/included.lua"))
    end)

    it("negates a function matcher", function()
      local m = matchers.not_(function(p)
        return p:match("%.test%.") ~= nil
      end)
      assert.is_true(m("main.lua"))
      assert.is_false(m("main.test.lua"))
    end)

    it("negates a table matcher", function()
      local m = matchers.not_({ "a.lua", "b.lua" })
      assert.is_true(m("/path/c.lua"))
      assert.is_false(m("/path/a.lua"))
      assert.is_false(m("/path/b.lua"))
    end)
  end)

  describe("literal", function()
    it("matches exact basename", function()
      local m = matchers.literal("config.lua")
      assert.is_true(m("/home/user/project/config.lua"))
      assert.is_true(m("config.lua"))
      assert.is_false(m("config.luax"))
      assert.is_false(m("my_config.lua"))
    end)

    it("does not treat string as pattern", function()
      local m = matchers.literal("file%.lua")
      assert.is_false(m("/path/file.lua"))
      assert.is_true(m("/path/file%.lua"))
    end)
  end)

  describe("pattern", function()
    it("matches Lua patterns against basename", function()
      local m = matchers.pattern("^test_.*%.lua$")
      assert.is_true(m("/path/test_something.lua"))
      assert.is_true(m("test_unit.lua"))
      assert.is_false(m("my_test_file.lua"))
      assert.is_false(m("test_something.py"))
    end)

    it("matches partial patterns", function()
      local m = matchers.pattern("spec")
      assert.is_true(m("/path/my_spec.lua"))
      assert.is_true(m("spec_file.lua"))
      assert.is_true(m("file_spec_test.lua"))
      assert.is_false(m("regular.lua"))
    end)
  end)

  describe("fn", function()
    it("wraps function as matcher", function()
      local custom = matchers.fn(function(path)
        return #path > 10
      end)
      assert.is_true(custom("/long/path/file.lua"))
      assert.is_false(custom("short"))
    end)
  end)
end)
